export const details= [
    {
        id:1,
        img:"https://www.peterposh.co.uk/wp-content/uploads/2024/01/bham-icon-template.jpg",
        text1:"Nailcote Hall, Warwickshire, CV7 7DE",
        text2:"Sunday 7th January 2024",
        button:"BIRMINGHAM SHOWROOM",
    },
    {
        id:2,
        img:"https://www.peterposh.co.uk/wp-content/uploads/2024/01/shrewsbury-fayre4.jpg",
        text1:"Albrighton Hall, Shrewsbury, SY4 3AG",
        text2:"Sunday 14th January 2024",
        button:"SHREWSBURY SHOWROOM",
    },
    {
        id:3,
        img:"https://www.peterposh.co.uk/wp-content/uploads/2024/01/minworth-fayre4.jpg",
        text1:"Coombe Abbey, Coventry, CV3 2AB",
        text2:"Sunday 14th January 2024",
        button:"WARWICK SHOWROOM",
    },
    {
        id:4,
        img:"https://www.peterposh.co.uk/wp-content/uploads/2024/01/knutsford-fayre4.jpg",
        text1:"The Oak Tree Of Peover, Knutsford, WA16 9SG",
        text2:"Sunday 14th January 2024",
        button:"KNUTSFORD SHOWROOM",
    },
    {
        id:5,
        img:"https://www.peterposh.co.uk/wp-content/uploads/2024/01/tettenahall-fayre4.jpg",
        text1:"The Mount Hotel, Wolverhampton, WV6 8HL",
        text2:"Sunday 14th January 2024",
        button:"TETTENHALL SHOWROOM",
    },
    {
        id:6,
        img:"https://www.peterposh.co.uk/wp-content/uploads/2024/01/bham-icon-template.jpg",
        text1:"CBS Arena, Coventry, CV6 6GE",
        text2:"Saturday 20th January 2024",
        button:"BIRMINGHAM SHOWROOM",
    },
    {
        id:7,
        img:"https://www.peterposh.co.uk/wp-content/uploads/2024/01/bham-icon-template.jpg",
        text1:"CBS Arena, Coventry, CV6 6GE",
        text2:"Sunday 21st January 2024",
        button:"BIRMINGHAM SHOWROOM",
    },
    {
        id:8,
        img:"https://www.peterposh.co.uk/wp-content/uploads/2024/01/bham-icon-template.jpg",
        text1:"Hogarths Hotel, Solihull, B93 8QE",
        text2:"Sunday 21st January 2024",
        button:"BIRMINGHAM SHOWROOM",
    },
    {
        id:9,
        img:"https://www.peterposh.co.uk/wp-content/uploads/2024/01/knutsford-fayre4.jpg",
        text1:"Mere Court Hotel, Knutsford, WA16 0RW",
        text2:"Sunday 28th January 2024",
        button:"KNUTSFORD SHOWROOM",
    },
    {
        id:10,
        img:"https://www.peterposh.co.uk/wp-content/uploads/2024/01/minworth-fayre4.jpg",
        text1:"Billesley Manor, Stratford-Upon-Avon, B49 6NF",
        text2:"Sunday 28th January 2024",
        button:"WARWICK SHOWROOM",
    },
    {
        id:11,
        img:"https://www.peterposh.co.uk/wp-content/uploads/2024/01/knutsford-fayre4.jpg",
        text1:"Nunsmere Hall Hotel, Northwich, CW8 2ES",
        text2:"Sunday 28th January 2024",
        button:"KNUTSFORD SHOWROOM",
    },
    {
        id:12,
        img:"https://www.peterposh.co.uk/wp-content/uploads/2024/01/telford-fayre4.jpg",
        text1:"Weston Park, Shifnal TF11 8LE",
        text2:"Sunday 28th January 2024",
        button:"TELFORD SHOWROOM",
    },
    {
        id:13,
        img:"https://www.peterposh.co.uk/wp-content/uploads/2024/01/knutsford-fayre4.jpg",
        text1:"Stock Farm Barn, Ashley, WA14 3QF",
        text2:"Sunday 4th February 2024",
        button:"KNUTSFORD SHOWROOM",
    },
    {
        id:14,
        img:"https://www.peterposh.co.uk/wp-content/uploads/2024/02/cheltenham-fayre4.jpg",
        text1:"Ellenborough Park, Cheltenham, GL52 3NJ",
        text2:"Sunday 4th February 2024",
        button:"CHELTENHAM SHOWROOM",
    },
    {
        id:15,
        img:"https://www.peterposh.co.uk/wp-content/uploads/2024/01/telford-fayre4.jpg",
        text1:"Park House, Shifnal TF11 9BA",
        text2:"Sunday 4th February 2024",
        button:"TELFORD SHOWROOM",
    },
    {
        id:16,
        img:"https://www.peterposh.co.uk/wp-content/uploads/2024/01/knutsford-fayre4.jpg",
        text1:"Liverpool Exhibition Centre, Liverpool, L3 4BX",
        text2:"Saturday 10th & Sunday 11th February 2024",
        button:"KNUTSFORD SHOWROOM",
    },
    {
        id:17,
        img:"https://www.peterposh.co.uk/wp-content/uploads/2024/01/telford-fayre4.jpg",
        text1:"High Grosvenor House, Claverley, WV15 5PG",
        text2:"Sunday 11th February 2024",
        button:"TELFORD SHOWROOM",
    },
    {
        id:18,
        img:"https://www.peterposh.co.uk/wp-content/uploads/2024/02/cheltenham-fayre4.jpg",
        text1:"Staffordshire County Showground, Cannock, WS12 1AG",
        text2:"Sunday 11th February 2024",
        button:"TETTENHALL SHOWROOM",
    },
    {
        id:19,
        img:"https://www.peterposh.co.uk/wp-content/uploads/2024/01/telford-fayre4.jpg",
        text1:"Best Western Plus Manor Hotel Meriden, Solihull, CV7 7NH",
        text2:"Sunday 18th February 2024",
        button:"BIRMINGHAM SHOWROOM",
    },
    {
        id:20,
        img:"https://www.peterposh.co.uk/wp-content/uploads/2024/01/knutsford-fayre4.jpg",
        text1:"AJ Bell Stadium, Eccles, M30 7EY",
        text2:"Sunday 18th February 2024",
        button:"KNUTSFORD SHOWROOM",
    },
    {
        id:21,
        img:"https://www.peterposh.co.uk/wp-content/uploads/2024/01/telford-fayre4.jpg",
        text1:"Moor Hall, Sutton Coldfield, B75 6LN",
        text2:"Sunday 18th February 2024",
        button:"BIRMINGHAM SHOWROOM",
    },
    {
        id:22,
        img:"https://www.peterposh.co.uk/wp-content/uploads/2024/01/telford-fayre4.jpg",
        text1:"Standon Hall, Staffordshire, ST21 6RA",
        text2:"Sunday 25th February 2024",
        button:"TELFORD SHOWROOM",
    },
    {
        id:23,
        img:"https://www.peterposh.co.uk/wp-content/uploads/2024/01/telford-fayre4.jpg",
        text1:"NEC National Wedding Show, B40 1NT",
        text2:"Friday 1st March 2024",
        button:"BIRMINGHAM SHOWROOM",
    },
    {
        id:24,
        img:"https://www.peterposh.co.uk/wp-content/uploads/2024/01/telford-fayre4.jpg",
        text1:"NEC National Wedding Show, B40 1NT",
        text2:"Saturday 2nd March 2024",
        button:"BIRMINGHAM SHOWROOM",
    },
    {
        id:25,
        img:"https://www.peterposh.co.uk/wp-content/uploads/2024/01/telford-fayre4.jpg",
        text1:"NEC National Wedding Show, B40 1NT",
        text2:"Sunday 3rd March 2024",
        button:"BIRMINGHAM SHOWROOM",
    },
    {
        id:25,
        img:"https://www.peterposh.co.uk/wp-content/uploads/2024/01/telford-fayre4.jpg",
        text1:"NEC National Wedding Show, B40 1NT",
        text2:"Sunday 3rd March 2024",
        button:"BIRMINGHAM SHOWROOM",
    },
    {
        id:26,
        img:"https://www.peterposh.co.uk/wp-content/uploads/2024/01/knutsford-fayre4.jpg",
        text1:"Chester Racecourse, Chester, CH1 4JD",
        text2:"Sunday 3rd March 2024",
        button:"KNUTSFORD SHOWROOM",
    },
    {
        id:27,
        img:"https://www.peterposh.co.uk/wp-content/uploads/2024/01/knutsford-fayre4.jpg",
        text1:"Carden Park, Cheshire, SY14 7HZ",
        text2:"Sunday 17th March 2024",
        button:"KNUTSFORD SHOWROOM",
    },
    {
        id:28,
        img:"https://www.peterposh.co.uk/wp-content/uploads/2024/02/cheltenham-fayre4.jpg",
        text1:"The Moat House, Stafford, ST17 0RJ",
        text2:"Sunday 17th March 2024",
        button:"TETTENHALL SHOWROOM",
    },
    {
        id:29,
        img:"https://www.peterposh.co.uk/wp-content/uploads/2024/01/telford-fayre4.jpg",
        text1:"The Moat House Hotel, Stafford ST17 0RJ",
        text2:"Sunday 17th March 2024",
        button:"TELFORD SHOWROOM",
    },
    {
        id:30,
        img:"https://www.peterposh.co.uk/wp-content/uploads/2024/01/minworth-fayre4.jpg",
        text1:"Swallows Nest Barn, Warwick, CV35 8AD",
        text2:"Sunday 17th March 2024",
        button:"WARWICK SHOWROOM",
    },
    {
        id:31,
        img:"https://www.peterposh.co.uk/wp-content/uploads/2024/02/cheltenham-fayre4.jpg",
        text1:"Aquarius Ballroom, Cannock, WS12 1BT",
        text2:"Sunday 17th March 2024",
        button:"TETTENHALL SHOWROOM",
    },
    {
        id:32,
        img:"https://www.peterposh.co.uk/wp-content/uploads/2024/01/bham-icon-template.jpg",
        text1:"Peter Posh Minworth Showroom Wedding Fayre, Minworth, B76 1DH",
        text2:"Sunday 24th March 2024",
        button:"BIRMINGHAM SHOWROOM",
    },
    {
        id:33,
        img:"https://www.peterposh.co.uk/wp-content/uploads/2024/01/shrewsbury-fayre4.jpg",
        text1:"Combermere Abbey, Whitchurch, SY13 4AJ",
        text2:"Sunday 24th March 2024",
        button:"SHREWSBURY SHOWROOM",
    },
    {
        id:34,
        img:"https://www.peterposh.co.uk/wp-content/uploads/2024/02/cheltenham-fayre4.jpg",
        text1:"Himley Hall, Dudley, DY3 4DF",
        text2:"Sunday 24th March 2024",
        button:"TETTENHALL SHOWROOM",
    },
    {
        id:35,
        img:"https://www.peterposh.co.uk/wp-content/uploads/2024/02/cheltenham-fayre4.jpg",
        text1:"Molineux Stadium, Wolverhampton, WV1 4QR",
        text2:"Sunday 14th April 2024",
        button:"TETTENHALL SHOWROOM",
    },
    {
        id:36,
        img:"https://www.peterposh.co.uk/wp-content/uploads/2024/01/knutsford-fayre4.jpg",
        text1:"Great Northern Wedding Show, Bolton Arena, BL6 6LB",
        text2:"Sunday 21st April 2024",
        button:"KNUTSFORD SHOWROOM",
    },
    {
        id:37,
        img:"https://www.peterposh.co.uk/wp-content/uploads/2024/02/cheltenham-fayre4.jpg",
        text1:"Village Hotel, Dudley, DY1 4TB",
        text2:"Sunday 21st April 2024",
        button:"TETTENHALL SHOWROOM",
    },
    {
        id:38,
        img:"https://www.peterposh.co.uk/wp-content/uploads/2024/02/cheltenham-fayre4.jpg",
        text1:"Himley Hall, Dudley, DY3 4DF",
        text2:"Sunday 11th August 2024",
        button:"TETTENHALL SHOWROOM",
    },
    {
        id:39,
        img:"https://www.peterposh.co.uk/wp-content/uploads/2024/02/cheltenham-fayre4.jpg",
        text1:"Staffordshire County Showground, Cannock, WS12 1AG",
        text2:"Sunday 29th September 2024",
        button:"TETTENHALL SHOWROOM",
    },
]